### ISSUE TITLE
CocoaPods build is broken

### ISSUE THREAD

**Issue by drdaz** [parse-community/Parse-SDK-iOS-OSX#1421] opened 2019-07-04 10:32 UTC
Updating an iOS app using the Parse SDK through CocoaPods currently breaks the build.

FBDSKCoreKit gets updated to 5.2.1, while FBSDKLoginKit remains at 4.44.1. There are breaking changes in FBSDKCoreKit v5.x vs FBSDKLoginKit v4.x. These are the first build errors I see:

<img width="356" alt="Screenshot 2019-07-04 at 12 31 49" src="https://user-images.githubusercontent.com/845731/60660293-bce55400-9e57-11e9-9689-9652569668cd.png">

**Comment by TomWFox** [comment] 2019-07-04 11:47
I believe this is a duplicate of #1411

**Closed** 2019-07-04 11:47 UTC

**Comment by drdaz** [comment] 2019-07-04 11:53
I discovered afterwards :)

**Comment by TomWFox** [comment] 2019-07-04 11:56
No problem 🙂
