### ISSUE TITLE
Xcode 12: Compiling frameworks fail

### ISSUE THREAD

**Issue by konkontos** [parse-community/Parse-SDK-iOS-OSX#1553] opened 2020-09-22 06:29 UTC
Just downloaded the 1.19.0 release.

After running `bundle exec rake package:frameworks` build process fails with the following error:

```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cookeecut/Downloads/Parse-SDK-iOS-OSX/build/Release-ios-iphoneos/Parse.framework/Parse and /Users/cookeecut/Downloads/Parse-SDK-iOS-OSX/build/Release-ios-iphonesimulator/Parse.framework/Parse have the same architectures (arm64) and can't be in the same fat output file
Failed to lipo iOS framework.
```

**Comment by drdaz** [comment] 2020-09-22 09:16
This looks like the same Xcode 12 issue we're seeing with Carthage. I can confirm I see the same behaviour locally.

**Comment by jesusmateos1234** [comment] 2020-10-28 20:40
Same, the workaround published on carthage doesn't work

**Comment by nickammo** [comment] 2020-11-26 11:55
Just modify build_task.rb by adding

if "#{@sdk}" =~ /iphonesimulator/i
    opts << "EXCLUDED_ARCHS=\"arm64\""
end

before

opts.compact.join(' ')

In xCode 12 Simulator build, similar to device build, contains "arm64" architecture.
So making a fat library (the one which works on both: device and Simulator) fails, since both contain the same architecture.
The fix is to simply exclude "arm64" architecture from Simulator build and keep it for device build only.

**Comment by cbaker6** [comment] 2020-12-19 15:45
Closing for now. Let us know if this issue happens again

**Closed by cbaker6** 2020-12-19 15:45 UTC

**Comment by cjosepha** [comment] 2022-04-24 11:14
This issue is still occurring on Parse 1.19.3 and Xcode 13.3
