### ISSUE TITLE
Inifnite loop caused by signing up or saving an anonymous user with username and password - happens if you had previously called saveEventually on an object with a pointer to this user.

### ISSUE THREAD

**Issue by brocoli** [parse-community/Parse-SDK-iOS-OSX#451] opened 2015-10-22 18:09 UTC
Bad things happen when you saveEventually an object with a pointer reference to an automatic user. The user stays in a state where isLazy = YES, authData[PFAnonymousUserAuthenticationType] == [NSNull null], self.linkedServiceNames.count == 0, and user.objectId is non-null. This state causes an infinite loop in 1.9.0, and additionally to that in the tip of the master as of writing, an infinite memory leak that grows very fast.

Furthermore, even when fixing the loop problem, a previously valid session becomes invalid after the signUp success.

---

== Steps to Reproduce ==
- setup an application in Parse.com
- substitute the applicationDidFinishLaunching in AppDelegate.m for this one in the starter project for OSX (substitute your application id and client key in the code)

``` Objective-c
    - (void)applicationDidFinishLaunching:(NSNotification *)notification {
        [Parse enableLocalDatastore];

        // ****************************************************************************
        // Uncomment and fill in with your Parse credentials:
        // [Parse setApplicationId:@"your_application_id" clientKey:@"your_client_key"];
        // ****************************************************************************

        [PFUser enableAutomaticUser];

        PFUser* user = [PFUser currentUser];

        PFObject* obj = [PFObject objectWithClassName:@"TestClass"];
        [obj setObject:user forKey:@"owner"];
        [obj saveEventually];

        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(10 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            user.username = @"fakeUser";
            user.password = @"fakePass";

            [user signUpInBackgroundWithBlock:^void (BOOL succeeded, NSError *error) {
                NSLog(@"signUpInBackgroundWithBlock's block called");
            }];
        });
    }
```

---

== Code walk ==

What's happening here is that our instance currentUser has isLazy == YES, and a non-null objectId.

After we set its username and password, it then has authData[PFAnonymousUserAuthenticationType] == [NSNull null], and isLazy == YES.

We then try to signUp the user.

signUpInBackground at PFUser.m:1194 is called, and it enters the if (self.objectId) clause. It enters the authData[PFAnonymousUserAuthenticationType] == [NSNull null] clause and calls PFObject's saveInBackgroundWithBlock.

saveInBackgroundWithBlock calls saveInBackground, which calls saveAsync at PFUser.m:1091

Here there's some task-queue manipulating code, but eventually it gets to PFUser.m:1100, after acquiring a lock. Since self.isLazy == YES, it will call resolveLazynessAsync.

now in resolveLazynessAsync at PFUser.m:413, it checks for self.linkedServiceNames.count == 0. This is true, since the Anonymous linked service has been set to null and removed from the linkedServiceNames array. So it calls signUpAsync.

signUpAsync at PFUser.m:469 has the same code as signUpInBackground. It checks for self.objectId, and then eventually calls saveAsync again at PFUser.m:1091.

This is the loop, since saveAsync has been called before without any change to the user object's fields, it will keep looping between signUpAsync and saveAsync. Notice that if we tried to save the user object instead of signing it up, the bug would still occur.

---

== Workaround and discussion ==

What we did to work around the bug (before we understood it correctly) was to modify the method stripAnonymity at PFUser.m:573. We changed it to this:

``` Objective-c
    - (void)stripAnonymity {
        @synchronized ([self lock]) {
            if ([PFAnonymousUtils isLinkedWithUser:self]) {
                NSString *authType = PFAnonymousUserAuthenticationType;

                [self.linkedServiceNames removeObject:authType];

                if (self.objectId) {
                    self.authData[authType] = [NSNull null];
                    self.isLazy = NO;
                } else {
                    [self.authData removeObjectForKey:authType];
                }
                dirty = YES;
            }
        }
    }
```

stripAnonymity is called when we set the user's username and password fields. The idea behind this is that if an user has username and password, it shouldn't be treated as an anonymous/automatic user anymore.

Basically, we added the  self.isLazy = NO;  line. This is not a correct fix, because if the signUp request fails, the self.isLazy flag should at least be reset to YES, and we don't understand if the state of the user object is correct while the signUp request is still in progress in this case. However, it avoids the infinite loop, so we're working with it for now.

---

After building the test case, we noticed that the function handleSignUpResultAsync PFUser.m:250 is never called, while if you save the user directly, it is called. This is significant because this function is normally what sets isLazy to NO in line 272.

---

There's another problem that happened after the signUp, however, even with the fix:

It's strange that the signUp-request-turned-into-save-request succeeded at all. Sure, we already have a session object because of the initial save back when the user was still anonymous, but the linked service Anonymous has been nulled out in the client's side. It seems to me that this session object should be invalid.

In fact, what happens is that the server saves the user object, and THEN deletes the now-invalid session object server-side. The result on the client's side is a successful "signUp", but the client now holds an invalid session. For now we worked around this by making a new logIn request after the successful "signUp" request.

The problem seems to be this transformation of a signUp into a save operation. It's intuitive to me that a successful signUp or linkWithAuthType should always set the current session to a valid one on the client's side, while a successful save shouldn't need to worry about this. Considering that the anonymous user is effectively "signed up" already in the server's side (linked to the auth service "Anonymous"), what we're really trying to do with the signUp is some kind of linkWithAuthType operation, where the "authType" is username/password authentication.

**Comment by richardjrossiii** [comment] 2015-10-22 20:10
First of all, thank you for the super detailed writeup.

This definitely isn't intended behavior, and I'll investigate this more thoroughly.

**Comment by brocoli** [comment] 2015-10-23 13:06
No problem, on the contrary, thanks for you guys for Parse.com being such an awesome service!

**Comment by henriquegemignani** [comment] 2015-11-06 18:42
Has there been any kind of progress on this?

**Comment by brocoli** [comment] 2015-11-18 16:11
It's been almost one month... has there been any progress on this issue?

**Comment by alexgo84** [comment] 2016-04-13 19:43
Thanks for the detailed description of the issue.

I believe that we encounter the same problem: 
1. A PFUser is created without no network access. A `Progress` object is created and a `Pointer` to it is saved on the PFUser. Both are pinned.
2. Try to `saveEventually` the user object.
3. Get internet connectivity and saveEventually succeeds. The `Progress` object is saved as well.
4. Try to signup - assign email, username and password to the user and call `signUpInBackground` or `saveInBackground`.
The result is that the call hangs in that method and memory inflates at a 0.5MB/Sec rate.

Looking for a workaround, will post here once I get something that works.

**Comment by nlutsenko** [comment] 2016-04-13 19:45
@alexgo84, if you could send me or @richardjrossiii a repro project - that would be tremendous help in debugging and finding the underlying issue.

**Comment by Tom-Fox1** [comment] 2019-03-28 16:23
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.

**Closed by Tom-Fox1** 2019-03-28 16:23 UTC
Labels: needs investigation
