### ISSUE TITLE
PFPush and PFInstallation for tvOS?

### ISSUE THREAD

**Issue by claesjacobsson** [parse-community/Parse-SDK-iOS-OSX#1043] opened 2016-09-25 13:37 UTC
Any idea when PFPush and PFInstallation will be available for tvOS?

**Comment by claesjacobsson** [comment] 2016-11-20 20:11
Bump.

**Comment by claesjacobsson** [comment] 2017-01-30 10:38
What is the status for this?

**Comment by mindgrub-rkoch** [comment] 2017-03-03 14:36
I too would like to know the status of this. 

I did notice there is a branch labeled nlutsenko.tvos.push, but it hasn't been updated in over a year.

**Comment by flovilmart** [comment] 2018-01-21 01:57
duplicate of #1198 , keeping the latest one open.

**Closed by flovilmart** 2018-01-21 01:57 UTC
Labels: duplicate
