### ISSUE TITLE
PFInstallation on tvOS?

### ISSUE THREAD

**Issue by claesjacobsson** [parse-community/Parse-SDK-iOS-OSX#1169] opened 2017-08-16 07:36 UTC
Will PFInstallation be included on tvOS? Among other things, my app is using channels to send push notifications so I really need it.

**Comment by matuella** [comment] 2017-09-21 18:51
Reaaaaaaallly need an update on this one, any plausible solution?

**Comment by flovilmart** [comment] 2017-09-21 22:09
You can probably get started on that and open a PR ;)

**Comment by matuella** [comment] 2017-09-22 00:55
I tried to fork and started to do what a branch called "" did, but I faile because of my shallow knowledge :( I'm actually working on a project that I've to deliver it ASAP

**Comment by flovilmart** [comment] 2017-09-22 00:57
And you should not depend on someone else to implement it, I’m sorry, but that’s not how open source work...

**Comment by matuella** [comment] 2017-09-22 01:00
I absolutely agree! Just wondering if someone got a solution, not blaming anything here :)

**Comment by flovilmart** [comment] 2018-01-21 01:07
There's an open PR for the Parse Push on TvOS, we should merge it soon enough

**Comment by flovilmart** [comment] 2018-01-21 01:57
duplicate of #1198 , keeping the latest one open.

**Closed by flovilmart** 2018-01-21 01:57 UTC
Labels: duplicate, enhancement, tvOS
