### ISSUE TITLE
Unable to save a change to an object's ACL

### ISSUE THREAD

**Issue by benpackard** [parse-community/Parse-SDK-iOS-OSX#1328] opened 2018-08-07 14:22 UTC
1. Fetch an existing `PFObject` and confirm that it is not publicly editable
2. Make it publicly editable
3. Save the object

Expected: The object is saved to the server as publicly editable
Actual: The object in memory is updated, but the change is not persisted

Example code:

```
// first fetch an object from the parse server, then...
print("before: \(object.acl?.hasPublicWriteAccess)") // "false"
object.acl?.hasPublicWriteAccess = true
object.saveInBackground { (success, error) in
    // confirm that success is true and error is nil
    print("after: \(object.acl?.hasPublicWriteAccess)") // "true" - object is updated client-side

    // now, re-fetch the same object or check it in Parse Dashboard. It is not saved as publicly editable.
}
```

**Comment by flovilmart** [comment] 2018-08-07 14:25
Ok so the object is actually not saved in the backend but no error is sent?

Can you reproduce with VERBOSE=1 on the server and provide the logs?

**Comment by benpackard** [comment] 2018-08-07 14:26
Correct. Yep I'll do that now and let you know.

**Comment by flovilmart** [comment] 2018-08-07 14:28
Thanks! Really appreciated!

**Comment by benpackard** [comment] 2018-08-07 14:57
I'm getting nothing at all logged for the save of the ACL. I've confirmed that the line of code is executed (and the closure fires). I've also confirmed that I'm seeing all the other usual verbose logging activity.

Some observations in case they are helpful:

- `isDirty` is `false` for the object after changing the ACL and before saving. Not sure if this is expected. If I change an additional property of the object before saving to make sure `isDirty` is `true`, this does not change anything.
- If I create a new object, save it, and then update the ACL, it works as expected. Only if the object is fetched from the server (and not created on the client) does the issue present itself.

I have some time to investigate further if you can think of anything else that might help.

**Comment by flovilmart** [comment] 2018-08-07 15:00
Interesting that's odd, is it something that're reproducible with the JS SDK?

**Comment by benpackard** [comment] 2018-08-07 15:02
I'm not sure, how might I test that out? I don't have a web app but I could try something in cloud code maybe?

**Comment by flovilmart** [comment] 2018-08-07 15:26
perhaps directly from cloud code / server locally. The JS SDK works well in node.

**Comment by benpackard** [comment] 2018-08-07 17:15
I created a cloud function and connected to a button in my UI. The cloud function seems to successfully save the ACL change.

Here is the cloud function I defined - be forewarned, I'm sure this is terrible javascript...

```

**Comment by flovilmart** [comment] 2018-08-07 17:17
Can you provide the Json representation of your object? What version of the server are your running?

**Comment by benpackard** [comment] 2018-08-07 17:42
Parse Server version is 2.8.2. 

As for a json representation, since the server isn't being sent anything when the client saves, I can't get anything from its log. Is there a way to generate it from the iOS client?

**Comment by flovilmart** [comment] 2018-08-07 17:43
I’ll try to reproduce from the server and provide a fix on top of 2.8.3 ASAP

**Comment by benpackard** [comment] 2018-08-07 17:44
Thanks, let me know if there's anything else that I can provide.

**Comment by flovilmart** [comment] 2018-08-07 17:45
The logs when running the server with VERBOSE=1 would really help :)

**Comment by benpackard** [comment] 2018-08-07 17:46
I don't get any logs remember! The SDK isn't calling through to the server when I save.

**Comment by flovilmart** [comment] 2018-08-07 17:46
From cloud code, you should have some logs no?

**Comment by benpackard** [comment] 2018-08-07 17:47
I do, but that works as expected- the ACL change persists.

**Comment by flovilmart** [comment] 2018-08-07 17:50
So I tried with the current server version the following code in JS:

```js
  fit('should let ACL ', async () => {
   // create an object
    const object = new Parse.Object('MyObject');
    // Set ACL to public read, no write
    const acl = new Parse.ACL();
    acl.setPublicReadAccess(true);
    acl.setPublicWriteAccess(false);
    object.set('title', 'a title');
    object.setACL(acl);
    // the save succeed
    await object.save();
    acl.setPublicWriteAccess(true);
    object.setACL(acl);
    // this save fails, as expected
    await object.save();
  });
```

So in the test case I can't reproduce the issue.

**Comment by benpackard** [comment] 2018-08-07 17:52
Right, but this isn't a server issue - I think it's in the iOS SDK. I too can successfully save the ACL change from JS (see above). The issue is that when saving from the iOS client, `save()` doesn't even reach the server - just returns successfully immediately.

**Comment by flovilmart** [comment] 2018-08-07 17:54
that's probably because the object isnt marked as dirty:

can you try:

```
let acl = object.acl
acl?.hasPublicWriteAccess = true
object.acl = acl // this will mark the object as dirty
object.save()
```

**Comment by benpackard** [comment] 2018-08-07 17:55
Yep that's my current workaround, it works. Is this expected behavior then?

**Comment by flovilmart** [comment] 2018-08-07 17:55
yes it's the expected one, as the PFObject doesn,t know it was mutated.

**Closed** 2018-08-07 17:56 UTC

**Comment by benpackard** [comment] 2018-08-07 18:00
(Thanks for all the help by the way).

**Comment by flovilmart** [comment] 2018-08-07 18:05
ACL is just a simple wrapper object, not 'active' inside the SDK. It's pretty much the same if you mutate local dictionary values in your object, it won't save unless you set it explicitely. At the moment, saving the ACL would need to have a back pointer to the parent which is unnecessary, but could be implemented.

**Comment by benpackard** [comment] 2018-08-07 18:18
I understand. In the absence of anything more useful to contribute, I wrote this up on StackOverflow in case someone else comes across the same thing.

https://stackoverflow.com/questions/51733025/changing-the-acl-on-a-pfobject-does-not-persist-to-the-parse-server

**Comment by flovilmart** [comment] 2018-08-07 18:43
Great idea to add it there! Thanks :)
