### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-SDK-iOS-OSX#1575] opened 2020-11-18 17:21 UTC
Would be usefull if I can fully deintegrate CocoaPods and use the Swift Package Manager.

Adding a Package.swift Manifest.

<img width="608" alt="Schermafbeelding 2020-11-18 om 18 20 55" src="https://user-images.githubusercontent.com/44820440/99564527-de9e9700-29ca-11eb-87f4-941b83561f84.png">

**Comment by TomWFox** [comment] 2020-11-18 21:26
This is a duplicate of #1453.

**Closed by TomWFox** 2020-11-18 21:26 UTC
