### ISSUE TITLE
Local and remote mismatch after saveEventually()

### ISSUE THREAD

**Issue by sobri909** [parse-community/Parse-SDK-iOS-OSX#772] opened 2016-01-18 09:55 UTC
``` swift
                let place = Place()
                place.visitsCount = 1
                place.visits.addObject(self)
                place.geoPoint = self.geoPoint
                place.radius = self.radius

                self.place = place

                place.saveEventually { (_) in
                    log("saved place: \(place.objectId)")
                    self.saveEventually { (_) in
                        log("my place: \(self.place!.objectId)")
                    }
                }
```

Produces this console output:

```
16:38:23.934 findAPlace() saved place: Optional("uaEnmBCK9e")
16:38:24.401 findAPlace() my place: Optional("uaEnmBCK9e")
```

But on Parse server side the object that is `self` in this context has a nil `place`. Which, as far as I can see, should be impossible. Surely someone is lying here. After a successful `saveEventually()` both local and remote should have identical objects?

In this particular class, `place` is declared thus:

``` swift
    @NSManaged var place: Place?
```

**Comment by sobri909** [comment] 2016-01-18 10:14
Oh this is curious. I changed it from `saveEventually()` to `saveInBackgroundWithBlock()`, and now it's working. 

The exact same console output, but this time the server side object matches on all fields.

So given that `saveEventually()` is doing some internal pinning / saving / unpinning thing, I wonder if it relates to my other problem (#768).

To be clear, this is what I changed it to: 

```swift
                place.saveEventually { (_) in
                    log("saved place: \(place.objectId)")
                    self.saveInBackgroundWithBlock() { (_) in
                        log("my place: \(self.place!.objectId)")
                    }
                }
```

The `Place` object isn't manually pinned locally, so I'm guessing that `saveEventually()` for that object works unhindered (it's certainly succeeding without mistakes) due to lack of conflict with manual pins.

But because `self` is manually pinned, it seems that using `saveEventually()` on it will result in mismatched fields between local and server, but `saveInBackgroundWithBlock()` doesn't cause mismatches. 

So yeah, in summary, it looks like `saveEventually()` on manually pinned objects is causing mismatches between local and server, but `saveInBackgroundWithBlock()` doesn't cause mismatches.

**Comment by sobri909** [comment] 2016-01-18 10:19
Oh, to be clear, I *have* been checking the `success` bools on those save callbacks and they are "succeeding". I'm just throwing them away in `(_)` in these particular code snippets for the sake of easier reading.

**Comment by sobri909** [comment] 2016-01-18 10:55
Huh. And now a `Place` has been saved with nil everything. Which should absolutely not be possible, if you look at the code above. Every field is given a value, then `saveEventually()` is called. It has saved to server land, but all fields are nil, including `visitsCount`, which is set to `1` in the code above. All field values have been lost. 

`saveEventually()` has issues? I'm not pinning `Places` locally at all, but they are references on `HistoryItem` objects, which are pinned.

**Comment by sobri909** [comment] 2016-01-18 11:09
Yeah, I just found a bunch of older bits of code through my project that were using `saveEventually()` on `Place` instances, and I'm fairly certain at least one of those fired while I was strolling around. So I'm near certain now that `saveEventually()` is losing field values when there's some combination of pinning going on.

**Comment by nlutsenko** [comment] 2016-01-19 03:10
Yup, sounds like you are running into issues directly related to `saveEventually()`, which potentially is also an issue behind #768, since we persist the objects as long as they are pending `saveEventually`.

I am going to investigate this, but is there any chance you can attach a code sample/project that reproduces the issue? Since you covered most of it - it would be a tremendous help.

**Comment by sobri909** [comment] 2016-01-19 03:23
> is there any chance you can attach a code sample/project that reproduces the issue?

That snippet at the top is I think all there is to it, with Parse being initiated in the AppDelegate thus:

```swift
        User.registerSubclass()
        HistoryItem.registerSubclass()
        Place.registerSubclass()
        ActivityEvent.registerSubclass()
        Parse.enableLocalDatastore()
        Parse.setApplicationId("...", clientKey: "...")
        PFUser.enableAutomaticUser()
```

I'll have a go at throwing together a sample project now with the minimum to reproduce it. But yeah, unless I'm missing something, that snippet at the top should be the heart of it.

**Comment by nlutsenko** [comment] 2016-01-19 03:24
(y) Looking forward to get a sample project, but the confirmation helps a lot. Thank you!

**Comment by sobri909** [comment] 2016-01-19 06:14
Sample project: [ParseTest.zip](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/files/95394/ParseTest.zip)

This is an imperfect test.

At one point I had it reproducing the difference between `saveEventually` and `saveInBackgroundWithBlock` 100% (with the former resulting in corrupt data while the latter not). Then I tried to dig deeper to see if I could narrow it down further, and #%@#$^ lost the 100% reproduction and I don't know which change did it.

Anyway, here's the notes:

- It obviously needs a Parse app id and client key in the AppDelegate.
- At the top of ViewController.swift there are some settings. Changing them produces different results.
- The current settings are such that it produces corrupt Place data (missing fields) every time.
- Loosely, the model structure is thus: 
   - Places have a HistoryItems relation
   - HistoryItems have an ActivityEvents array
   - HistoryItems and ActivityEvents are being explicitly pinned, but Places are not
- The delayBeforeTriggeringAFail is just a hacky way to change whether the fail triggering happens immediately, after pinning, or after saving, or even while a save might be happening.

This doesn't exactly match my app's logic or flow. I just put in enough basic similarity to be able to trigger the problem (or at least one sort of similar). A big difference in my app is that the HistoryItems are not unsaved (though they might have an ActivityEvent in their activities array that is unsaved). But I couldn't get the problem to trigger with that combination of factors.

So ... yeah, I'm still not completely pinning it down. I'm only reproducing something that looks superficially similar. 

There's Parse warnings / errors in the console about trying to add a relation to a non pointer. I'm not getting those in my app (presumably because the HistoryItems are saved). Which is another indicator that this isn't a perfect reproduction.

But yeah, this is the best I can do so far. If you fiddle around with the settings at the top of ViewController to produce different correct / incorrect results, maybe you'll be able to find a better answer than I have.

**Comment by sobri909** [comment] 2016-01-19 06:15
Oh, you'll obviously need to run `pod install` first.

**Comment by sobri909** [comment] 2016-01-19 06:17
Oh, and ignore the stuff like this for now: 

```swift
print("an unsaved ActivityEvent that isn't dirty. this shouldn't happen")
```

I'm going to reuse the same project to test #768, so those particular bits are relevant to that, but not to this task.

**Comment by nlutsenko** [comment] 2016-01-19 08:04
Took a quick look - looks sane and easy to understand.
Will dive deep tomorrow and let you know how it goes.
Thanks for putting it all together!

**Comment by Tom-Fox1** [comment] 2019-03-28 16:58
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.

**Closed by Tom-Fox1** 2019-03-28 16:58 UTC
Labels: needs investigation
