### ISSUE TITLE
findObjectsInBackgroundWithBlock Segmentation Fault: 11

### ISSUE THREAD

**Issue by SpringFoundation** [parse-community/Parse-SDK-iOS-OSX#1394] opened 2019-03-03 03:25 UTC
Had a look through the issues and found people with similar issues to mine but they are all a little outdated and the solutions don't really work for me...

```
    func loadPosts() {
        let query = PFQuery(className:"Post")
        query.order(byDescending: "createdAt")
        query.includeKey("user")
        query.limit = initialLimit
        query.findObjectsInBackgroundWithBlock { (objects: [PFObject]?, error: NSError?) -> Void in
            if Error != nil {
                print(Error)
            } else {
                print("Successfully retrieved \(objects!.count) posts. - Home View Controller")
                self.posts = objects
                
                print("\(self.initialLimit) is now the limit")
                self.tableView.reloadData()
            }
        } as! PFQueryArrayResultBlock
    }
```

**Comment by Tom-Fox1** [comment] 2019-03-04 13:52
So I did a little bit of digging and I think the issue is with having `as! PFQueryArrayResultBlock`.

If you remove this you then get the following error:
```
Cannot convert value of type '([PFObject]?, NSError?) -> ()' to expected argument type 'PFQueryArrayResultBlock?' (aka 'Optional<(Optional<Array<PFObject>>, Optional<Error>) -> ()>')
```
With the suggested fix of inserting `as! PFQueryArrayResultBlock`. We can fix this error by instead changing `NSError` to `Error`. The argument type should be `Error`, I think the suggested fix is wrong (at least in this case). I may not be correct, as I'm not very knowledgeable about this SDK, but it's my best guess.

The code for the whole function should now be as shown below:
```swift
func loadPosts() {
    let query = PFQuery(className:"Post")
    query.order(byDescending: "createdAt")
    query.includeKey("user")
    query.limit = initialLimit
    query.findObjectsInBackgroundWithBlock { (objects: [PFObject]?, error: Error?) -> Void in
        if error != nil {
            print(error)
        } else {
            print("Successfully retrieved \(objects!.count) posts. - Home View Controller")
            self.posts = objects!
            
            print("\(self.initialLimit) is now the limit")
            self.tableView.reloadData()
        }
    }
}
```

**Comment by Tom-Fox1** [comment] 2019-03-04 13:53
Hopefully, that fixes it, let me know if it works.

**Comment by Tom-Fox1** [comment] 2019-03-08 17:35
Could you close this if it has solved your issue.

**Comment by Tom-Fox1** [comment] 2019-03-18 16:07
I'm closing this now, please let me know if you are still experiencing this issue and I can reopen if needed.

**Closed by Tom-Fox1** 2019-03-18 16:07 UTC
