### ISSUE TITLE
NSLocation Issue in iOS SDK - Please check

### ISSUE THREAD

**Issue by alexsdi** [parse-community/Parse-SDK-iOS-OSX#1344] opened 2018-09-03 07:41 UTC
Hello Developer,

I use parse for cloud storage purpose in my iOS APP. When I uploaded the binary to itunes conenct with Parse SDK installed apple sends me an automated message like bellow. This issue have been a month from now. When i removed the SDK from pod i don' t delivered this message. 

Also I have the same issue with more than one project.

Has anyone else the same issue? What text can i add to info.plist to make apple approve my project.

" Dear Developer,

We identified one or more issues with a recent delivery for your 
app XXXXX. Your delivery was successful, but you 
may wish to correct the following issues in your next delivery:

"Missing Purpose String in Info.plist File. Your app's code 
references one or more APIs that access sensitive user data. The 
app's Info.plist file should contain a 
NSLocationAlwaysUsageDescription key with a user-facing purpose 
string explaining clearly and completely why your app needs the 
data. Starting spring 2019, all apps submitted to the App Store 
that access user data will be required to include a purpose 
string.If you're using external libraries or SDKs, they may 
reference APIs that require a purpose string. While your app might 
not use these APIs, a purpose string is still required. You can 
contact the developer of the library or SDK and request they 
release a version of their code that doesn't contain the APIs. 

 After you’ve corrected the issues, you can use Xcode or 
 Application Loader to upload a new binary to iTunes Connect.

 Best regards,

 The App Store Team"

Please resolve the issue and let me know, Thanks...

**Comment by flovilmart** [comment] 2018-09-03 11:32
Duplicate of #1343 . Closing

**Closed by flovilmart** 2018-09-03 11:32 UTC
