### ISSUE TITLE
XCode 12 incompatible block pointer

### ISSUE THREAD

**Issue by Anon-Mars** [parse-community/Parse-SDK-iOS-OSX#1550] opened 2020-09-20 09:02 UTC
since we updated xcode to version 12, parse is showing this error attached.

<img width="705" alt="Screen Shot 2020-09-20 at 11 58 22" src="https://user-images.githubusercontent.com/71587119/93707643-14451200-fb39-11ea-9927-bb0b9e4fc911.png">

**Comment by TomWFox** [comment] 2020-09-20 09:53
This is a duplicate of #1526, the issue was fixed by #1527 which is now available on the newly released version 1.19.0.

**Closed by TomWFox** 2020-09-20 09:53 UTC
