### ISSUE TITLE
Unable to build app in xcode 14

### ISSUE THREAD

**Issue by onlinedeveloper4u** [parse-community/Parse-SDK-iOS-OSX#1661] opened 2022-09-28 07:36 UTC
App is running successfully on xcode 13 but build failed when running app on xcode 14 with these parse errors.

<img width="513" alt="Screen Shot 2022-09-28 at 12 34 58 PM" src="https://user-images.githubusercontent.com/71644910/192717200-f6a4d4ae-8366-44ff-abbc-2bef6aa51e13.png">

**Comment by mtrezza** [comment] 2022-09-28 09:05
I suggest to build xcframeworks with carthage, if that is an alternative for you. It works also with Xcode 14.

**Comment by mtrezza** [comment] 2022-09-28 09:25
I'm closing this as it doesn't use the issue template provided and is there considered to be a general duplicate of existing issues.

**Closed** 2022-09-28 09:39 UTC
Labels: type:question
