### ISSUE TITLE
Add installation using SPM

### ISSUE THREAD

**Issue by Sofrik** [parse-community/Parse-SDK-iOS-OSX#1546] opened 2020-09-17 10:05 UTC
Hello! Could you add SDK addition to the project using SPM (Swift Package Manager)

**Comment by TomWFox** [comment] 2020-09-17 16:39
This is a duplicate of #1453. As far as I know no one is working on this or planning to do so. Feel free to submit a PR - I'm sure other contributors would be happy to help if needed.

**Closed by TomWFox** 2020-09-17 16:39 UTC
