### ISSUE TITLE
PFUser unexpected behavior

### ISSUE THREAD

**Issue by damianvdk** [parse-community/Parse-SDK-iOS-OSX#1340] opened 2018-08-28 20:41 UTC
Every time I login and I rerun my xcode project on ios, it appears like the user is not logged in but I am logged in.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [Parse enableDataSharingWithApplicationGroupIdentifier:@"group.novem.Peral"];
    
    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"KkVj6i7pw6Kp0YcBdtfSXvnXrEO8ldQVaWPOMB6z";
        configuration.clientKey = @"7SKcRmd2lLHVegEdo3KrZhuiahak2GAT7YyTeJum";
        configuration.server = @"https://parseapi.back4app.com/";
    }]];
    
    NSLog(@"Parse | Peral is connecting to the server...");
    PFInstallation *currentInstallation = [PFInstallation currentInstallation];
    [currentInstallation saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        if (succeeded) {
            if (!error) {
                NSLog(@"Parse | Peral is sucessfully connected to the server");
            }
        }
        else {
            NSLog(@"Parse | Peral failed to connect to the server");
            [Novem logErrorWithFunction:_cmd class:[self class] errorNumber:1 error:error completion:nil];
        }
    }];
    
    NSLog(@"[PFUser currentUser].email: %@", [PFUser currentUser].email);
    NSLog(@"[PFUser currentUser].username: %@", [PFUser currentUser].username);
    NSLog(@"[PFUser currentUser]: %@", [PFUser currentUser]);
    
return YES;
}
``` 

This is what I get in the console

```
2018-08-28 22:38:30.358965+0200 Peral[776:86241] Parse | Peral is connecting to the server...
2018-08-28 22:38:30.524390+0200 Peral[776:86241] [PFUser currentUser].email: (null)
2018-08-28 22:38:30.524618+0200 Peral[776:86241] [PFUser currentUser].username: (null)
2018-08-28 22:38:30.524832+0200 Peral[776:86241] [PFUser currentUser]: <PFUser: 0x283bf1f80, objectId: new, localId: (null)> {
}
2018-08-28 22:38:30.529576+0200 Peral[776:86241] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283bf7380> (Domain: group.novem.Peral, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
2018-08-28 22:38:30.539059+0200 Peral[776:86241] {
}
2018-08-28 22:38:30.769581+0200 Peral[776:86241] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-08-28 22:38:30.770395+0200 Peral[776:86241] [MC] Reading from public effective user settings.
2018-08-28 22:38:30.898289+0200 Peral[776:86418] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x11fd7d2d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-08-28 22:38:30.898331+0200 Peral[776:86418] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x11fd7d2d0] 4830172680:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-08-28 22:38:30.898350+0200 Peral[776:86418] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x11fd7d2d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-08-28 22:38:30.898366+0200 Peral[776:86418] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x11fd7d2d0] 4830172680:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-08-28 22:38:30.906132+0200 Peral[776:86418] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x11fd7d2d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-08-28 22:38:30.906168+0200 Peral[776:86418] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x11fd7d2d0] 4830172680:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-08-28 22:38:30.906240+0200 Peral[776:86418] [BoringSSL] boringssl_session_errorlog(224) [C1.1:2][0x11fd7d2d0] [boringssl_session_read] SSL_ERROR_SSL(1): operation failed within the library
2018-08-28 22:38:30.906261+0200 Peral[776:86418] [BoringSSL] boringssl_session_handshake_error_print(205) [C1.1:2][0x11fd7d2d0] 4830172680:error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE:/BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.200.32/ssl/ssl_lib.cc:1081:
2018-08-28 22:38:31.154604+0200 Peral[776:86241] Parse | Peral is sucessfully connected to the server
```

But this results in my app crashing because the email is null but I need the email. 

I am running iOS 12 BETA 10 and Xcode 10 BETA 6

**Comment by flovilmart** [comment] 2018-08-28 20:48
Thanks for your report

> But this results in my app crashing because the email is null but I need the email.

Can you provide the stack trace of the crash?

From what I see from the lines 2 and 3 of your logs, email and username are null, as the user has never been saved.

You also will want to investigate this log: 
```
[User Defaults] Couldn't read values in CFPrefsPlistSource<0x283bf7380> (Domain: group.novem.Peral, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
```

If you remove this line `[Parse enableDataSharingWithApplicationGroupIdentifier:@"group.novem.Peral"];` does it help?

**Comment by damianvdk** [comment] 2018-08-28 21:02
So I removed this line:
`[Parse enableDataSharingWithApplicationGroupIdentifier:@"group.novem.Peral"];`
But this didn't help.

The problem with the crash is that I don't know the origin of it, I just know that it's probably because the email turns nil.

**Comment by flovilmart** [comment] 2018-08-28 21:18
Well, did this error start occurring recently? Is it occurring in other iOS versions? 
For all I can say, there is no user logged in your app, and your app is expecting one. 

From the code you share, it is not in the snippet that it crashes.

There are some clues: can’t refresh an object that hasn’t been saved etc... which points to logical issues in your own code.


The crash is pretty explicit, and the stack should tell you the origin of it.

**Comment by damianvdk** [comment] 2018-08-28 21:26
I started implementing Parse yesterday so I don't know, but you are saying I am doing something wrong with the user?

**Comment by flovilmart** [comment] 2018-08-28 21:31
Well, I don't know at all. This **should be working** correctly (otherwise we'd have many issues as you can imagine), unless you're doing something wrong. 

Can you try with non-beta iOS versions please?

Are you able to share a demo project that shows the issue?

If I understand correctly, you log your user in through calling `[PFUser signUp:]` somewhere but when the app restarts the user is not there anymore?

**Comment by damianvdk** [comment] 2018-08-28 21:41
Yes indeed, I am really searching all day to find what I am doing wrong, but I can't find anything. 

About the demo, my project is big and I started switching from Google Firebase to Parse cause I want to expand to multiple platforms.

So when I login, everything works great but, I can even leave the app and go back. But when the app closes it seems like the user doesn't work correctly. `[PFUser currentUser]` doesn't return null, but `[PFUser currentUser].email` or `[PFUser currentUser].username` returns null. So this what I experience.

I will now update iOS to beta 11 and I'll be back tommorow.

Sorry to bother and I hope we can fix this

**Comment by flovilmart** [comment] 2018-08-28 21:45
> I will now update iOS to beta 11 and I'll be back tommorow.

Please report with a non beta iOS version (latest iOS 11).

> So when I login, everything works great but, I can even leave the app and go back. But when the app closes it seems like the user doesn't work correctly. 

How can you be so sure of that?

also what version of the SDK are you using?

> About the demo, my project is big and I started switching from Google Firebase to Parse cause I want to expand to multiple platforms.

Well, You should probably be able to take 20 minutes and recreate on a small, empty project the issue if it saves you hours of debugging. If you want anyone else to be able to help you, you should produce this demo project.

Until then, I'll close the issue.

**Closed by flovilmart** 2018-08-28 21:45 UTC

**Comment by flovilmart** [comment] 2018-08-28 22:12
@damianvdk I've tried to reproduce your issue with:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        Parse.initialize(with: ParseClientConfiguration(block: { (config) in
            config.applicationId = "myAppId"
            config.server = "https://sleepy-reef-27444.herokuapp.com/parse"
            config.isLocalDatastoreEnabled = true
        }))
        PFUser.enableAutomaticUser()
        let currentUser = PFUser.current()
        print("\(currentUser?.objectId) \(currentUser?.email)")
        _ = try? PFUser.logIn(withUsername: "florent", password: "password")

        return true
    }
```

And unfortunately, the user is very well present when restarting the app. So I would say with confidence that the issue lies in your own code OR is specific to a particular beta version.

Xcode: Version 10.0 beta 5 (10L221o)
Simulator: OS 12.0 (16A5339e)

**Comment by damianvdk** [comment] 2018-08-29 09:33
ok, I am sorry I think I found what I was doing wrong. So first of all Parse apparently requires internet connection and I need to reauthenticate a user when launching the app

**Comment by flovilmart** [comment] 2018-08-29 11:26
> I need to reauthenticate a user when launching the app

No you don’t. A user’s session information is persisted into the keychain in order to be available on restarts.

> Parse apparently required internet connection:

Yes, but you can use the local datastore in order to save objects locally. 

Users and Installation are persisted locally independently. 

Did you read the docs, guides and API references on https://docs.parseplatform.org?

**Comment by flovilmart** [comment] 2018-08-29 11:52
I don’t know, perhaps, perhaps not. As I shared the code snippet, it worked for me, did you try it? Upon the second launch the user is properly set.

**Comment by damianvdk** [comment] 2018-08-29 12:00
`    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"KkVj6i7pw6Kp0YcBdtfSXvnXrEO8ldQVaWPOMB6z";
        configuration.clientKey = @"7SKcRmd2lLHVegEdo3KrZhuiahak2GAT7YyTeJum";
        configuration.server = @"https://parseapi.back4app.com/";
        configuration.localDatastoreEnabled = YES;
    }]];
    [PFUser enableAutomaticUser];
    PFUser *currentUser = [PFUser currentUser];
    NSLog(@"ObjectId: %@ | Email: %@", currentUser.objectId, currentUser.email);
    
    NSLog(@"Parse | Peral is connecting to the server...");
    PFInstallation *currentInstallation = [PFInstallation currentInstallation];
    [currentInstallation saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        if (succeeded) {
            if (!error) {
                NSLog(@"Parse | Peral is sucessfully connected to the server");
            }
        }
        else {
            NSLog(@"Parse | Peral failed to connect to the server");
            [Novem logErrorWithFunction:_cmd class:[self class] errorNumber:1 error:error completion:nil];
        }
    }];`

I translated your code to objective c and runned my app (after I logged in). And I still get this in the log.

`ObjectId: (null) | Email: (null)`

**Comment by damianvdk** [comment] 2018-08-29 12:06
` if (!currentUser) [PFUser logInWithUsername:@"vdkdamian" password:@"myPassword"];`

I added this line right behind `NSLog(@"ObjectId: %@ | Email: %@", currentUser.objectId, currentUser.email);`  and the on when I re-run, I still get this log `ObjectId: (null) | Email: (null)`

I'll now create a new project and try it.

**Comment by flovilmart** [comment] 2018-08-29 12:08
CurrentUser is never nil so your login call is never run

**Comment by damianvdk** [comment] 2018-08-29 12:32
` [PFUser logInWithUsername:@"vdkdamian" password:@"myPassword"];`

I changed it to this and when I run it I am logged in, but whenever I remove that line, `ObjectId: (null) | Email: (null)` i get this

**Comment by damianvdk** [comment] 2018-08-29 12:33
I need to say that I removed this line: `[PFUser enableAutomaticUser];` because I dont want anonymous users

**Comment by flovilmart** [comment] 2018-08-29 12:35
So, i’ll go back to my previous demand, which was to to provide a demo project that shows the issue. I also asked you to try on non beta iOS. 

Please provide what was asked.

**Comment by damianvdk** [comment] 2018-08-29 12:38
I created a new project, did the exact same as on the other project, But it works fine. I also use the same device, same xcode version and same ios 12 beta 11

**Comment by flovilmart** [comment] 2018-08-29 12:39
So the problem is in your code in your existing project, not in the Parse SDK.

**Comment by damianvdk** [comment] 2018-08-29 12:51
So I am almost sure that it's not my code, but I disable Keychain Sharing in my current project, I ran it and it worked fine. I now re-enabled Keychain Sharing and it is working fine.

I want to mention that I was not using the default Keychain Group name but now I am and it works, could it be because of this?

**Comment by flovilmart** [comment] 2018-08-29 13:02
I’m not sure why you’d need keychain sharing in the first place. The iOS SDK relies on keychain to store securely the user Info.

From what you mention, your project was misconfigured, as default project configuration just work. So yes it was your code/project not the implementation of the SDK.

This is precisely why I asked you to provide a demo project. If you cannot reproduce the issue with a demo project, that means that your current project has bad code, or is misconfigured. 

Also, you could have mentioned earlier that you tried in a new project, and didn’t manage to reproduce.

**Comment by flovilmart** [comment] 2018-08-29 14:59
For future reference, would you be able to open a PR here or on the docs repository that explains what happened in your case, how to reproduce the issue and how to fix it? Other users may encounter it and your experience might be helpful for them. A demo project that reproduce the issue would also be welcome! if the keychain sharing configuration can be a source of issues when misconfigured, it is interesting to know. But in order to make sure your issue comes from a misconfigured keychain, you should be able to reproduce it.

**Comment by damianvdk** [comment] 2018-08-29 15:42
Ok, so to point things out now. The problem is now fixed but I changed my keychain path to a default path.
<img width="1726" alt="schermafbeelding 2018-08-29 om 14 51 23" src="https://user-images.githubusercontent.com/8835052/44798313-6fea7e80-abb1-11e8-977f-daf53c9f12fa.png">

I also experienced something this code gave an error about something unsaved child. And this caused the user to logout.

`NSString *deviceName = [@"theDevice Name"];
PFUser *currentUser = [PFUser currentUser];
NSString *userObjectID = currentUser.objectId;

PFObject *registeredDevice = [PFObject objectWithClassName:@"Devices"];
registeredDevice.ACL = [PFACL ACLWithUser:currentUser];
registeredDevice[@"name"] = deviceName;

    PFUser *user = [PFUser currentUser];
    PFRelation *relation = [user relationForKey:@"devices"];
    [relation addObject:registeredDevice];
    
PFQuery *query = [PFQuery queryWithClassName:@"Devices"];
[query whereKey:@"name" equalTo:deviceName];
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
    if ((!error) && (objects) && ([objects count] > 0)) {
        PFObject *queriedDevice = [objects firstObject];
        queriedDevice.ACL = [PFACL ACLWithUser:currentUser];
        queriedDevice[@"name"] = deviceName;
        
        [queriedDevice saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
            if (error) {
                
            }
        }];
    } else {
        [registeredDevice saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
            if (error) {
                
            }
            else {
                [user saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                }];
            }
        }];
    }
    }];`

When I changed it to this it was fixed: 

`    NSString *deviceName = [@"theDevice Name"];
    PFUser *currentUser = [PFUser currentUser];
    NSString *userObjectID = currentUser.objectId;
    
    PFObject *registeredDevice = [PFObject objectWithClassName:@"Devices"];
    registeredDevice.ACL = [PFACL ACLWithUser:currentUser];
    registeredDevice[@"name"] = deviceName;
    
    PFQuery *query = [PFQuery queryWithClassName:@"Devices"];
    [query whereKey:@"name" equalTo:deviceName];
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if ((!error) && (objects) && ([objects count] > 0)) {
            PFObject *queriedDevice = [objects firstObject];
            queriedDevice.ACL = [PFACL ACLWithUser:currentUser];
            queriedDevice[@"name"] = deviceName;
            
            [queriedDevice saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                if (error) {
                    
                }
            }];
        } else {
            PFUser *user = [PFUser currentUser];
            PFRelation *relation = [user relationForKey:@"devices"];
            [relation addObject:registeredDevice];
            
            [registeredDevice saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                if (error) {
                    
                }
                else {
                    [user saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
                    }];
                }
            }];
        }
    }];`

**Comment by flovilmart** [comment] 2018-08-29 16:17
> The problem is now fixed but I changed my keychain path to a default path.

What do you mean by that? what was the path before? What is it now? Can you explicitely reproduce the issue by putting another value in there?

**Comment by damianvdk** [comment] 2018-08-29 16:41
So by default path I mean `com.novem.Peral` this is a value that gets filled in by xcode when you toggle Keychain Sharing on. Before this path I used `nvmPeral`. 

And what about the other thing I metioned, is it normal behavior that this causes my app to not recognize the user on launch?

**Comment by flovilmart** [comment] 2018-08-29 16:56
About that other thing, I am not sure what’s wrong as it’s not accompanied with logs, stack traces or anything else. I’m not entirely sure but again, please provide a demo project or even better, a PR with a test that shows that user session information is lost from the keychain under certain conditions.

**Comment by flovilmart** [comment] 2018-08-29 17:12
@damianvdk so I tried using: 'no-group' as the keychain sharing identifier in the demo app, and it still worked as expected. <img width="659" alt="snap" src="https://user-images.githubusercontent.com/364568/44803698-30aa3680-ab8d-11e8-9261-47876d2729e2.png">

Based on this, I'm really not sure what's wrong with your project.

**Comment by damianvdk** [comment] 2018-08-29 17:15
forget the keychain, I thought the keychain fixed it but I can't reproduce the problem either.
Either way, if somebody might have the same issue, try toggling the keychain sharing on and off and maybe using another name.

**Comment by flovilmart** [comment] 2018-08-29 17:39
You issue is interesting, and is related to the fact that the code you're using is corrupting the 'currentUser' which can't be saved anymore. As you example shows, you're trying to attach an unsaved object to the user. When doing that, you're corrupting the local data, and the SDK is unable to keep the user stored locally on disk as it has relational data pointing to an unsaved object (which is not allowed, and why you had an error logged).

Now, what can the SDK do about it? Nothing. Unless you're willing to spend some time finding a work around.

What should you do about it? well, ensure that your code doesn't error with relational data.

**Comment by damianvdk** [comment] 2018-08-29 17:48
ok, so now we know what was going wrong.

**Comment by flovilmart** [comment] 2018-08-29 17:50
Well, yes, and again, assuming it was part of the SDK was only leading you into the wrong direction. It’s also a great reminder that when s/o asks for a demo project to repro the issue it’s most likely to make you understand where in your code things fail.

**Comment by damianvdk** [comment] 2018-08-29 20:09
Ok, i'll keep it in mind, but can I please ask you one question about a code that I really can't find anything about on the web? 
I would like to know how I use this function.

`getDataDownloadStreamInBackgroundWithProgressBlock`

**Comment by flovilmart** [comment] 2018-08-29 20:59
Did you have a look at all the unit tests? Also: the 1st google search yeilds: http://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFFile.html#/c:objc(cs)PFFile(im)getDataDownloadStreamInBackgroundWithProgressBlock:
